In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('customer_churn.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3083 entries, 0 to 3082
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   CustomerID                   3083 non-null   int64  
 1   Churn                        3083 non-null   int64  
 2   Tenure                       2930 non-null   float64
 3   PreferredLoginDevice         3083 non-null   object 
 4   CityTier                     3083 non-null   int64  
 5   WarehouseToHome              2929 non-null   float64
 6   PreferredPaymentMode         3083 non-null   object 
 7   Gender                       3083 non-null   object 
 8   HourSpendOnApp               2933 non-null   float64
 9   NumberOfDeviceRegistered     3083 non-null   int64  
 10  PreferedOrderCat             3083 non-null   object 
 11  SatisfactionScore            3083 non-null   int64  
 12  MaritalStatus                3083 non-null   object 
 13  NumberOfAddress   

In [3]:
df.isnull().sum()

CustomerID                       0
Churn                            0
Tenure                         153
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                154
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 150
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    131
CouponUsed                     126
OrderCount                     128
DaySinceLastOrder              166
CashbackAmount                   0
dtype: int64

In [4]:
df.drop_duplicates(inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3078 entries, 0 to 3082
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   CustomerID                   3078 non-null   int64  
 1   Churn                        3078 non-null   int64  
 2   Tenure                       2925 non-null   float64
 3   PreferredLoginDevice         3078 non-null   object 
 4   CityTier                     3078 non-null   int64  
 5   WarehouseToHome              2924 non-null   float64
 6   PreferredPaymentMode         3078 non-null   object 
 7   Gender                       3078 non-null   object 
 8   HourSpendOnApp               2928 non-null   float64
 9   NumberOfDeviceRegistered     3078 non-null   int64  
 10  PreferedOrderCat             3078 non-null   object 
 11  SatisfactionScore            3078 non-null   int64  
 12  MaritalStatus                3078 non-null   object 
 13  NumberOfAddress   

In [5]:
df['Tenure'] = df['Tenure'].fillna(round(df['Tenure'].mean(), 1))
df['WarehouseToHome'] = df['WarehouseToHome'].fillna(round(df['WarehouseToHome'].mean(), 1))
df['HourSpendOnApp'] = df['HourSpendOnApp'].fillna(round(df['HourSpendOnApp'].mean(), 1))
df['OrderAmountHikeFromlastYear'] = df['OrderAmountHikeFromlastYear'].fillna(round(df['OrderAmountHikeFromlastYear'].mean(), 1))
df['CouponUsed'] = df['CouponUsed'].fillna(round(df['CouponUsed'].mean(), 1))
df['OrderCount'] = df['OrderCount'].fillna(round(df['OrderCount'].mean(), 1))
df['DaySinceLastOrder'] = df['DaySinceLastOrder'].fillna(round(df['DaySinceLastOrder'].mean(), 1))

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3078 entries, 0 to 3082
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   CustomerID                   3078 non-null   int64  
 1   Churn                        3078 non-null   int64  
 2   Tenure                       3078 non-null   float64
 3   PreferredLoginDevice         3078 non-null   object 
 4   CityTier                     3078 non-null   int64  
 5   WarehouseToHome              3078 non-null   float64
 6   PreferredPaymentMode         3078 non-null   object 
 7   Gender                       3078 non-null   object 
 8   HourSpendOnApp               3078 non-null   float64
 9   NumberOfDeviceRegistered     3078 non-null   int64  
 10  PreferedOrderCat             3078 non-null   object 
 11  SatisfactionScore            3078 non-null   int64  
 12  MaritalStatus                3078 non-null   object 
 13  NumberOfAddress   

In [6]:
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

PreferredLoginDevice PreferredPaymentMode Gender    PreferedOrderCat  \
0             Computer           Debit Card   Male        Mobile Phone   
1         Mobile Phone           Debit Card   Male             Grocery   
2         Mobile Phone          Credit Card   Male  Laptop & Accessory   
3                Phone             E wallet   Male              Mobile   
4             Computer           Debit Card   Male  Laptop & Accessory   

  MaritalStatus  
0        Single  
1       Married  
2        Single  
3       Married  
4      Divorced

In [7]:
obj_df["PreferredLoginDevice"] = obj_df["PreferredLoginDevice"].astype('category')
obj_df["PreferredPaymentMode"] = obj_df["PreferredPaymentMode"].astype('category')
obj_df["Gender"] = obj_df["Gender"].astype('category')
obj_df["PreferedOrderCat"] = obj_df["PreferedOrderCat"].astype('category')
obj_df["MaritalStatus"] = obj_df["MaritalStatus"].astype('category')
obj_df.dtypes

PreferredLoginDevice    category
PreferredPaymentMode    category
Gender                  category
PreferedOrderCat        category
MaritalStatus           category
dtype: object

In [8]:
obj_df["PreferredLoginDevice_cat"] = obj_df["PreferredLoginDevice"].cat.codes
obj_df["PreferredPaymentMode_cat"] = obj_df["PreferredPaymentMode"].cat.codes
obj_df["Gender_cat"] = obj_df["Gender"].cat.codes
obj_df["PreferedOrderCat_cat"] = obj_df["PreferedOrderCat"].cat.codes
obj_df["MaritalStatus_cat"] = obj_df["MaritalStatus"].cat.codes
obj_df

PreferredLoginDevice PreferredPaymentMode  Gender    PreferedOrderCat  \
0                Computer           Debit Card    Male        Mobile Phone   
1            Mobile Phone           Debit Card    Male             Grocery   
2            Mobile Phone          Credit Card    Male  Laptop & Accessory   
3                   Phone             E wallet    Male              Mobile   
4                Computer           Debit Card    Male  Laptop & Accessory   
...                   ...                  ...     ...                 ...   
3078         Mobile Phone           Debit Card    Male             Grocery   
3079         Mobile Phone           Debit Card    Male             Fashion   
3080         Mobile Phone           Debit Card    Male              Mobile   
3081             Computer           Debit Card  Female              Mobile   
3082         Mobile Phone          Credit Card    Male  Laptop & Accessory   

     MaritalStatus  PreferredLoginDevice_cat  PreferredPaymentMode_cat  \
0           Single                         0                         4   
1          Married                         1                         4   
2           Single                         1                         3   
3          Married                         2                         5   
4         Divorced                         0                         4   
...            ...                       ...                       ...   
3078       Married                         1                         4   
3079        Single                         1                         4   
3080       Married                         1                         4   
3081      Divorced                         0                         4   
3082       Married                         1                         3   

      Gender_cat  PreferedOrderCat_cat  MaritalStatus_cat  
0              1                     4                  2  
1              1                     1                  1  
2              1                     2                  2  
3              1                     3                  1  
4              1                     2                  0  
...          ...                   ...                ...  
3078           1                     1                  1  
3079           1                     0                  2  
3080           1                     3                  1  
3081           0                     3                  0  
3082           1                     2                  1  

[3078 rows x 10 columns]

In [9]:
df['PreferredLoginDevice'] = obj_df['PreferredLoginDevice_cat']
df['PreferredPaymentMode'] = obj_df['PreferredPaymentMode_cat']
df['Gender'] = obj_df['Gender_cat']
df['PreferedOrderCat'] = obj_df['PreferedOrderCat_cat']
df['MaritalStatus'] = obj_df['MaritalStatus_cat']
df

CustomerID  Churn  Tenure  PreferredLoginDevice  CityTier  \
0          54023      1     1.0                     0         1   
1          50266      0    16.0                     1         1   
2          54985      0    16.0                     1         1   
3          52029      1     0.0                     2         3   
4          50084      0    13.0                     0         1   
...          ...    ...     ...                   ...       ...   
3078       51224      0    13.0                     1         1   
3079       51396      1    11.0                     1         1   
3080       52017      0     9.1                     1         1   
3081       50355      1     0.0                     0         1   
3082       53803      1     2.0                     1         1   

      WarehouseToHome  PreferredPaymentMode  Gender  HourSpendOnApp  \
0                31.0                     4       1             4.0   
1                18.0                     4       1             2.0   
2                36.0                     3       1             3.0   
3                15.8                     5       1             2.0   
4                15.0                     4       1             3.0   
...               ...                   ...     ...             ...   
3078              6.0                     4       1             3.0   
3079              6.0                     4       1             3.0   
3080             16.0                     4       1             2.0   
3081             13.0                     4       0             2.9   
3082              9.0                     3       1             3.0   

      NumberOfDeviceRegistered  PreferedOrderCat  SatisfactionScore  \
0                            5                 4                  1   
1                            4                 1                  4   
2                            6                 2                  1   
3                            4                 3                  4   
4                            4                 2                  2   
...                        ...               ...                ...   
3078                         3                 1                  5   
3079                         4                 0                  3   
3080                         3                 3                  4   
3081                         3                 3                  3   
3082                         4                 2                  4   

      MaritalStatus  NumberOfAddress  Complain  OrderAmountHikeFromlastYear  \
0                 2                3         1                         25.0   
1                 1                2         0                         11.0   
2                 2                6         0                         20.0   
3                 1                2         1                         18.0   
4                 0               10         0                         14.0   
...             ...              ...       ...                          ...   
3078              1                3         0                         11.0   
3079              2               10         1                         13.0   
3080              1                2         0                         14.0   
3081              0                2         1                         16.0   
3082              1                6         0                         12.0   

      CouponUsed  OrderCount  DaySinceLastOrder  CashbackAmount  
0            2.0         2.0                1.0             149  
1            0.0         3.0                9.0             243  
2            2.0         2.0                1.0             168  
3            0.0         1.0                0.0             124  
4            1.0         1.0                2.0             149  
...          ...         ...                ...             ...  
3078         1.8        11.0               16.0             268  
3079         0.0  

In [10]:
X = df.drop(['Churn'], axis =1).values
y = df['Churn'].values

print(X.shape)
print(y.shape)

(3078, 19)
(3078,)


In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=12)

In [12]:
#SVM 模型

from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

svm = make_pipeline(StandardScaler(), SVR(kernel='linear', degree=1, gamma='auto',C=1.0, epsilon=0.2))


In [13]:
from sklearn.svm import SVR
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)
svm_score = svm.score(X_test, y_test)
svm_score

0.34378543804843065

In [14]:
#Logistic Regression 模型

from sklearn import preprocessing, linear_model

logistic_regr = linear_model.LogisticRegression()
logistic_regr.fit(X_train, y_train)
logistic_pred = logistic_regr.predict(X_test)
logistic_score = logistic_regr.score(X_test, y_test)
logistic_score

0.8141650422352177

In [15]:
# Decision tree 模型

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

In [16]:
clf = tree.DecisionTreeClassifier()
clf.fit(X_train, y_train)
tree_pred = clf.predict(X_test)
tree_score = clf.score(X_test, y_test)
tree_score

0.8674463937621832

In [17]:
svm_pred

array([0.90425604, 0.52482675, 0.64545545, ..., 0.7410076 , 0.18730402,
       0.6236839 ])

In [18]:
# meanings of hyperparameter, in SVM model,
# c = penalty for each misclassified data point
# gamma = controls the distance of influence of a single training point

In [19]:
# 請以 Accuracy 評估同一模型在不同超參數設定下於訓練資料及測試資料上的表現
# 測試SVM模型中 C = 1, 10, 100的score

svm_10 = make_pipeline(StandardScaler(), SVR(kernel='linear', degree=1, gamma='auto',C=10.0, epsilon=0.2))
svm_10.fit(X_train, y_train)
svm_pred_10 = svm_10.predict(X_test)
svm_score_10 = svm_10.score(X_test, y_test)
svm_score_10

0.34361978300921947

In [20]:
svm_100 = make_pipeline(StandardScaler(), SVR(kernel='linear', degree=1, gamma='auto',C=100.0, epsilon=0.2))
svm_100.fit(X_train, y_train)
svm_pred_100 = svm_100.predict(X_test)
svm_score_100 = svm_100.score(X_test, y_test)
svm_score_100

0.34398976692878924

In [21]:
compare = {
    "SVM model": ["c = 1", "c = 10", "c = 100"],
    "score": [svm_score, svm_score_10, svm_score_100],
}

compare_df = pd.DataFrame(compare)
compare_df

SVM model     score
0     c = 1  0.343785
1    c = 10  0.343620
2   c = 100  0.343990

In [22]:
#請以 Accuracy 比較 三個模型的表現 

score_dict = {
    "model" : ["SVM", "logistic regression", "decision tree"],
    "score" : [svm_score, logistic_score, tree_score]
}

score_df = pd.DataFrame(score_dict)
score_df

model     score
0                  SVM  0.343785
1  logistic regression  0.814165
2        decision tree  0.867446

In [23]:
#請列出三個模型的 Confusion matrix，並簡述其意義

from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn import metrics

In [24]:
y_test_int = y_test.astype(np.int64)
svm_pred_int = svm_pred.astype(np.int64)

In [25]:
#logistic regression confusion matrix

logistic_cm = metrics.confusion_matrix(y_test_int, logistic_pred)
print(logistic_cm)

[[929 131]
 [155 324]]


In [26]:
#SVM confusion matrix

svm_cm = metrics.confusion_matrix(y_test_int, svm_pred_int)
print(svm_cm)

[[1060    0]
 [ 477    2]]


In [27]:
#decision tree confusion matrix

tree_cm = metrics.confusion_matrix(y_test_int, tree_pred)
print(tree_cm)

[[958 102]
 [102 377]]


In [28]:
# 混淆矩陣的左上和右下是預測正確，分別代表預測的結果 = 實際的結果，例如左上可能是預測為A，實際值也為A；右下為預測是B實際也為B
# 右上左下是預測錯誤，右上為預測是B實際為A，左下為預測是A實際為B
